# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
LocalHost = "服务端ip地址"
import socket
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
class Client:
    client_socket = None

    def __init__(self):
        self.initialize_socket()

    def initialize_socket(self):
        # 创建套接字
        self.clientsocket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(457, 304)
        self.labelstatus = QtWidgets.QLabel(Dialog)
        self.labelstatus.setGeometry(QtCore.QRect(20, 40, 111, 51))
        self.labelstatus.setTextFormat(QtCore.Qt.PlainText)
        self.labelstatus.setScaledContents(False)
        self.labelstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelstatus.setWordWrap(False)
        self.labelstatus.setObjectName("labelstatus")
        self.labelStatus = QtWidgets.QLabel(Dialog)
        self.labelStatus.setGeometry(QtCore.QRect(160, 50, 101, 31))
        self.labelStatus.setText("")
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.labelStatus2 = QtWidgets.QLabel(Dialog)
        self.labelStatus2.setGeometry(QtCore.QRect(40, 80, 101, 61))
        self.labelStatus2.setTextFormat(QtCore.Qt.AutoText)
        self.labelStatus2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus2.setObjectName("labelStatus2")
        self.labelTem = QtWidgets.QLabel(Dialog)
        self.labelTem.setGeometry(QtCore.QRect(90, 150, 72, 15))
        self.labelTem.setObjectName("labelTem")
        self.labelWet = QtWidgets.QLabel(Dialog)
        self.labelWet.setGeometry(QtCore.QRect(90, 190, 72, 15))
        self.labelWet.setObjectName("labelWet")
        self.labelLight = QtWidgets.QLabel(Dialog)
        self.labelLight.setGeometry(QtCore.QRect(90, 230, 72, 15))
        self.labelLight.setObjectName("labelLight")
        self.lineEditTem = QtWidgets.QLineEdit(Dialog)
        self.lineEditTem.setGeometry(QtCore.QRect(140, 150, 101, 21))
        self.lineEditTem.setObjectName("lineEditTem")
        self.lineEditWet = QtWidgets.QLineEdit(Dialog)
        self.lineEditWet.setGeometry(QtCore.QRect(140, 190, 101, 21))
        self.lineEditWet.setObjectName("lineEditWet")
        self.lineEditLight = QtWidgets.QLineEdit(Dialog)
        self.lineEditLight.setGeometry(QtCore.QRect(140, 230, 101, 21))
        self.lineEditLight.setObjectName("lineEditLight")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 120, 111, 71))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ludeng"))
        self.labelstatus.setText(_translate("Dialog", "路灯状态："))
        self.labelStatus2.setText(_translate("Dialog", "环境状态："))
        self.labelTem.setText(_translate("Dialog", "温度："))
        self.labelWet.setText(_translate("Dialog", "湿度："))
        self.labelLight.setText(_translate("Dialog", "亮度："))
        self.pushButton.setText(_translate("Dialog", "发送"))
        self.pushButton.clicked.connect(self.SendMessage)

    def SendMessage(self):
        self.client = Client()
        self.client.initialize_socket()
        data_t = self.labelTem.text()
        data_w = self.labelWet.text()
        data_l = self.labelLight.text()
        self.client.clientsocket.sendto(data_t.encode("utf8"), (LocalHost, 8000))
        self.client.clientsocket.sendto(data_w.encode("utf8"), (LocalHost, 8000))
        self.client.clientsocket.sendto(data_l.encode("utf8"), (LocalHost, 8000))
        if data_l == '#' or data_w == 'w' or data_t == '#':
            exit(0)
        self.recvfrom_server()

    def recvfrom_server(self):
        self.status, self.address = self.client.clientsocket.recvfrom(1024)
        if self.status == b'open':
            self.labelStatus.setText("Open")
        else:
            self.labelStatus.setText("Close")

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())