# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientThread.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import random
import time

LocalHost = "127.0.0.1"
import socket
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import *
def randomMes():
    tep = str(random.randint(-20, 40))
    light = str(random.randint(0, 101))
    wet = str(random.randint(0, 101))
    return tep, light, wet

class Client(QtCore.QThread):
    client_socket = None
    _signal_data = pyqtSignal(tuple)
    _signal_result = pyqtSignal(str)

    def __init__(self):
        super(Client, self).__init__()
        self.client_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    def __del__(self):
        self.wait()

    def run(self):
        while True:
            data = randomMes()
            self._signal_data.emit(data)
            data_t = data[0]
            data_l = data[1]
            data_w = data[2]
            self.client_socket.sendto(data_t.encode("utf8"), (LocalHost, 8000))
            self.client_socket.sendto(data_w.encode("utf8"), (LocalHost, 8000))
            self.client_socket.sendto(data_l.encode("utf8"), (LocalHost, 8000))
            self.status, self.address = self.client_socket.recvfrom(1024)
            if self.status == b'open':
                self._signal_result.emit("Open")
            else:
                self._signal_result.emit("Close")
            time.sleep(5)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(457, 304)
        self.labelstatus = QtWidgets.QLabel(MainWindow)
        self.labelstatus.setGeometry(QtCore.QRect(20, 40, 111, 51))
        self.labelstatus.setTextFormat(QtCore.Qt.PlainText)
        self.labelstatus.setScaledContents(False)
        self.labelstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelstatus.setWordWrap(False)
        self.labelstatus.setObjectName("labelstatus")
        self.labelStatus = QtWidgets.QLabel(MainWindow)
        self.labelStatus.setGeometry(QtCore.QRect(160, 50, 101, 31))
        self.labelStatus.setText("")
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.labelStatus2 = QtWidgets.QLabel(MainWindow)
        self.labelStatus2.setGeometry(QtCore.QRect(30, 80, 101, 61))
        self.labelStatus2.setTextFormat(QtCore.Qt.AutoText)
        self.labelStatus2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus2.setObjectName("labelStatus2")
        self.labelTem = QtWidgets.QLabel(MainWindow)
        self.labelTem.setGeometry(QtCore.QRect(90, 150, 72, 15))
        self.labelTem.setObjectName("labelTem")
        self.labelWet = QtWidgets.QLabel(MainWindow)
        self.labelWet.setGeometry(QtCore.QRect(90, 190, 72, 15))
        self.labelWet.setObjectName("labelWet")
        self.labelLight = QtWidgets.QLabel(MainWindow)
        self.labelLight.setGeometry(QtCore.QRect(90, 230, 72, 15))
        self.labelLight.setObjectName("labelLight")
        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(300, 120, 111, 71))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(140, 140, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(140, 180, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(140, 220, 61, 31))
        self.label_3.setObjectName("label_3")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ludeng"))
        self.labelstatus.setText(_translate("MainWindow", "路灯状态："))
        self.labelStatus2.setText(_translate("MainWindow", "环境状态："))
        self.labelTem.setText(_translate("MainWindow", "温度："))
        self.labelWet.setText(_translate("MainWindow", "湿度："))
        self.labelLight.setText(_translate("MainWindow", "亮度："))
        self.pushButton.setText(_translate("MainWindow", "开启"))
        self.label.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "0%"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.socketThread = None
        self.pushButton.clicked.connect(self.start_login)

    def start_login(self):
        if not self.socketThread:
            self.socketThread = Client()
            self.socketThread._signal_data.connect(self.call_back)  # 绑定修改室内状态信息
            self.socketThread._signal_result.connect(self.displayresult)  # 绑定修改灯状态信息
            self.socketThread.start()

    def call_back(self, data):
        self.label.setText(str(data[0]))
        self.label_2.setText(str(data[2]) + "%")
        self.label_3.setText(str(data[1]))

    def displayresult(self, result):
        self.labelStatus.setText(str(result))





if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
